title: ICCV 2025 Workshop on Generative AI for Storytelling (AISTORY)
description: Official page for the ICCV 2025 Workshop on Generative AI for Storytelling (AISTORY), held in Honolulu, Hawai'i, Oct 19-23, 2025.
theme: just-the-docs
url: https://aistory2025.github.io
baseurl: ""  # Use "/iccv2025-workshop" if project-specific repo
permalink: pretty

# Enable markdown plugins
markdown: kramdown
kramdown:
  input: GFM  # GitHub Flavored Markdown

# Navigation
nav_order: 1
aux_links:
  "ICCV 2025": https://iccv.thecvf.com
  "GitHub Repository": https://aistory2025.github.io
